/*
 * Copyright (c) 2022 Bounce developed by alanmcilwaine and maxwebbnz
 * All rights reserved.
 */

import { user } from '../../firebase/fb.user'

export default function Header({ media, title, comment, student }) {
    return (
        <>
            <div
                className="inline-flex space-x-4 items-center justify-start mb-10 mt-10"
                style={{ width: "1280", height: 56 }}
            >
                {media ?
                    <img
                        className="w-20 h-20 rounded-lg"
                        src={media}
                        alt="Media for PDF"
                    />
                    : null}
                <div
                    className="inline-flex flex-col space-y-2 items-start justify-start"
                    style={{ width: 951, height: 56 }}
                >
                    {student ?
                        <p
                            className="text-2xl font-bold leading-7 text-gray-900"
                            style={{ width: 951 }}
                        >
                            Report generated for {student.name}
                        </p>
                        : <p
                            className="text-3xl font-bold leading-7 text-gray-900"
                            style={{ width: 800 }}
                        >
                            Report generated for {title}
                        </p>}

                    <div className="flex space-x-1.5 items-center justify-start">
                        {student ?
                            <p className="text-lg font-medium leading-tight text-gray-500">
                                {" "}
                                {student.studentID}
                            </p>
                            : null}
                    </div>
                    <p className="text-lg font-medium leading-tight text-gray-500">
                        Report generated by {user.name} on 25/08/2022
                    </p>

                </div>
            </div>


        </>
    );
}